BROKER_URL = 'amqp://guest:guest@localhost:5672//'
CELERY_TIMEZONE = "Asia/Shanghai"
BROKER_HEARTBEAT = None
CELERYD_CONCURRENCY = 10
CELERY_DISABLE_RATE_LIMITS = True

CELERY_TASK_SERIALIZER = 'pickle'
CELERY_ACCEPT_CONTENT = ["pickle"]
CELERY_RESULT_SERIALIZER = 'pickle'
# CELERY_TASK_RESULT_EXPIRES = 60 * 60 * 24   # 任务过期时间
